/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as MockupsIndexRouteImport } from './routes/mockups/index'
import { Route as MockupsInboxRouteImport } from './routes/mockups/inbox'
import { Route as MockupsPoolArisanRouteImport } from './routes/mockups/pool-arisan'
import { Route as MockupsPoolCostSplitRouteImport } from './routes/mockups/pool-cost-split'
import { Route as MockupsRoomRouteImport } from './routes/mockups/room'
import { Route as MockupsRoomsRouteImport } from './routes/mockups/rooms'
import { Route as AuthedRoomsIndexRouteImport } from './routes/_authed/rooms/index'
import { Route as AuthedRoomsJoinRouteImport } from './routes/_authed/rooms/join'
import { Route as AuthedRoomsRoomIdIndexRouteImport } from './routes/_authed/rooms/$roomId/index'
import { Route as AuthedRoomsRoomIdPoolsPoolIdIndexRouteImport } from './routes/_authed/rooms/$roomId/pools/$poolId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsIndexRoute = MockupsIndexRouteImport.update({
  id: '/mockups/',
  path: '/mockups/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsInboxRoute = MockupsInboxRouteImport.update({
  id: '/mockups/inbox',
  path: '/mockups/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsPoolArisanRoute = MockupsPoolArisanRouteImport.update({
  id: '/mockups/pool-arisan',
  path: '/mockups/pool-arisan',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsPoolCostSplitRoute = MockupsPoolCostSplitRouteImport.update({
  id: '/mockups/pool-cost-split',
  path: '/mockups/pool-cost-split',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsRoomRoute = MockupsRoomRouteImport.update({
  id: '/mockups/room',
  path: '/mockups/room',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsRoomsRoute = MockupsRoomsRouteImport.update({
  id: '/mockups/rooms',
  path: '/mockups/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoomsIndexRoute = AuthedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsJoinRoute = AuthedRoomsJoinRouteImport.update({
  id: '/rooms/join',
  path: '/rooms/join',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsRoomIdIndexRoute = AuthedRoomsRoomIdIndexRouteImport.update({
  id: '/rooms/$roomId/',
  path: '/rooms/$roomId/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsRoomIdPoolsPoolIdIndexRoute =
  AuthedRoomsRoomIdPoolsPoolIdIndexRouteImport.update({
    id: '/rooms/$roomId/pools/$poolId/',
    path: '/rooms/$roomId/pools/$poolId/',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mockups/inbox': typeof MockupsInboxRoute
  '/mockups/pool-arisan': typeof MockupsPoolArisanRoute
  '/mockups/pool-cost-split': typeof MockupsPoolCostSplitRoute
  '/mockups/room': typeof MockupsRoomRoute
  '/mockups/rooms': typeof MockupsRoomsRoute
  '/mockups/': typeof MockupsIndexRoute
  '/rooms/join': typeof AuthedRoomsJoinRoute
  '/rooms/': typeof AuthedRoomsIndexRoute
  '/rooms/$roomId/': typeof AuthedRoomsRoomIdIndexRoute
  '/rooms/$roomId/pools/$poolId/': typeof AuthedRoomsRoomIdPoolsPoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mockups/inbox': typeof MockupsInboxRoute
  '/mockups/pool-arisan': typeof MockupsPoolArisanRoute
  '/mockups/pool-cost-split': typeof MockupsPoolCostSplitRoute
  '/mockups/room': typeof MockupsRoomRoute
  '/mockups/rooms': typeof MockupsRoomsRoute
  '/mockups': typeof MockupsIndexRoute
  '/rooms/join': typeof AuthedRoomsJoinRoute
  '/rooms': typeof AuthedRoomsIndexRoute
  '/rooms/$roomId': typeof AuthedRoomsRoomIdIndexRoute
  '/rooms/$roomId/pools/$poolId': typeof AuthedRoomsRoomIdPoolsPoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mockups/inbox': typeof MockupsInboxRoute
  '/mockups/pool-arisan': typeof MockupsPoolArisanRoute
  '/mockups/pool-cost-split': typeof MockupsPoolCostSplitRoute
  '/mockups/room': typeof MockupsRoomRoute
  '/mockups/rooms': typeof MockupsRoomsRoute
  '/mockups/': typeof MockupsIndexRoute
  '/_authed/rooms/join': typeof AuthedRoomsJoinRoute
  '/_authed/rooms/': typeof AuthedRoomsIndexRoute
  '/_authed/rooms/$roomId/': typeof AuthedRoomsRoomIdIndexRoute
  '/_authed/rooms/$roomId/pools/$poolId/': typeof AuthedRoomsRoomIdPoolsPoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/mockups/inbox'
    | '/mockups/pool-arisan'
    | '/mockups/pool-cost-split'
    | '/mockups/room'
    | '/mockups/rooms'
    | '/mockups/'
    | '/rooms/join'
    | '/rooms/'
    | '/rooms/$roomId/'
    | '/rooms/$roomId/pools/$poolId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/mockups/inbox'
    | '/mockups/pool-arisan'
    | '/mockups/pool-cost-split'
    | '/mockups/room'
    | '/mockups/rooms'
    | '/mockups'
    | '/rooms/join'
    | '/rooms'
    | '/rooms/$roomId'
    | '/rooms/$roomId/pools/$poolId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/auth/callback'
    | '/mockups/inbox'
    | '/mockups/pool-arisan'
    | '/mockups/pool-cost-split'
    | '/mockups/room'
    | '/mockups/rooms'
    | '/mockups/'
    | '/_authed/rooms/join'
    | '/_authed/rooms/'
    | '/_authed/rooms/$roomId/'
    | '/_authed/rooms/$roomId/pools/$poolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MockupsInboxRoute: typeof MockupsInboxRoute
  MockupsPoolArisanRoute: typeof MockupsPoolArisanRoute
  MockupsPoolCostSplitRoute: typeof MockupsPoolCostSplitRoute
  MockupsRoomRoute: typeof MockupsRoomRoute
  MockupsRoomsRoute: typeof MockupsRoomsRoute
  MockupsIndexRoute: typeof MockupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/': {
      id: '/mockups/'
      path: '/mockups'
      fullPath: '/mockups/'
      preLoaderRoute: typeof MockupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/inbox': {
      id: '/mockups/inbox'
      path: '/mockups/inbox'
      fullPath: '/mockups/inbox'
      preLoaderRoute: typeof MockupsInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/pool-arisan': {
      id: '/mockups/pool-arisan'
      path: '/mockups/pool-arisan'
      fullPath: '/mockups/pool-arisan'
      preLoaderRoute: typeof MockupsPoolArisanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/pool-cost-split': {
      id: '/mockups/pool-cost-split'
      path: '/mockups/pool-cost-split'
      fullPath: '/mockups/pool-cost-split'
      preLoaderRoute: typeof MockupsPoolCostSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/room': {
      id: '/mockups/room'
      path: '/mockups/room'
      fullPath: '/mockups/room'
      preLoaderRoute: typeof MockupsRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/rooms': {
      id: '/mockups/rooms'
      path: '/mockups/rooms'
      fullPath: '/mockups/rooms'
      preLoaderRoute: typeof MockupsRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/rooms/': {
      id: '/_authed/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthedRoomsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms/join': {
      id: '/_authed/rooms/join'
      path: '/rooms/join'
      fullPath: '/rooms/join'
      preLoaderRoute: typeof AuthedRoomsJoinRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms/$roomId/': {
      id: '/_authed/rooms/$roomId/'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof AuthedRoomsRoomIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms/$roomId/pools/$poolId/': {
      id: '/_authed/rooms/$roomId/pools/$poolId/'
      path: '/rooms/$roomId/pools/$poolId'
      fullPath: '/rooms/$roomId/pools/$poolId/'
      preLoaderRoute: typeof AuthedRoomsRoomIdPoolsPoolIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedRoomsJoinRoute: typeof AuthedRoomsJoinRoute
  AuthedRoomsIndexRoute: typeof AuthedRoomsIndexRoute
  AuthedRoomsRoomIdIndexRoute: typeof AuthedRoomsRoomIdIndexRoute
  AuthedRoomsRoomIdPoolsPoolIdIndexRoute: typeof AuthedRoomsRoomIdPoolsPoolIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedRoomsJoinRoute: AuthedRoomsJoinRoute,
  AuthedRoomsIndexRoute: AuthedRoomsIndexRoute,
  AuthedRoomsRoomIdIndexRoute: AuthedRoomsRoomIdIndexRoute,
  AuthedRoomsRoomIdPoolsPoolIdIndexRoute:
    AuthedRoomsRoomIdPoolsPoolIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MockupsInboxRoute: MockupsInboxRoute,
  MockupsPoolArisanRoute: MockupsPoolArisanRoute,
  MockupsPoolCostSplitRoute: MockupsPoolCostSplitRoute,
  MockupsRoomRoute: MockupsRoomRoute,
  MockupsRoomsRoute: MockupsRoomsRoute,
  MockupsIndexRoute: MockupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
